directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework: all
skip-check:
- CKV_AWS_111 #Ensure IAM policies does not allow write access without constraints
- CKV_AWS_109 #Ensure IAM policies does not allow permissions management / resource exposure without constraints
- CKV_AWS_144 #Ensure that S3 bucket has cross-region replication enabled
- CKV_AWS_18  #Ensure the S3 bucket has access logging enabled
- CKV_AWS_145 #Ensure that S3 buckets are encrypted with KMS by default. NOTE:: Resource for this feature not currently detected by checkov though buckets are encrypted.
